### PR TITLE
The author has not signed-off on the contribution #38

### LINKED ISSUE #38: The author has not signed-off on the contribution
The signed-off-by validation is failing if it's not the last line:

```
commit e8c6da660643bcc77ea33d399f6a90e7c6d11e6b (HEAD -> cguindon/test/eca)
Author: Christopher Guindon <chris.guindon@eclipse-foundation.org>
Date:   Tue Dec 8 16:06:52 2020 -0500

    add readme.md
    
    Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>
    Change-Id: I139e2d803770ef65e55645e2d499731ffb749300
```

Result:

```
 ! [remote rejected] HEAD -> refs/for/master (commit e8c6da6: The contributor must sign-off on the contribution.)
error: failed to push some refs to '../webdev/devops'
```

The workaround is to move the sign-off-by section after the Change-Id. However, we can't expect our users to do that. The requirement is simply to include the in the footer section of a commit message.

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by mbarbero** [comment]
IMO, a positive and negative unit test is required here.

**Comment by chrisguindon** [comment]
@mbarbero I agree! 

I created this PR to see if our existing tests were going to fail but it looks like we are not running any of our tests when a PR is submitted.

**Comment by autumnfound** [comment]
To cover this case, we would need an additional test in our test suite that checks how it handles multiple footer entries. All of our tests currently only have 1 footer line each at most

**Comment by mbarbero** [comment]
It does run the tests: https://github.com/EclipseFdn/git-eca-rest-api/blob/master/Jenkinsfile#L41 (the `package` goal runs the tests), but there is no test covering this feature good enough to detect regression or this particular use case.

**Comment by mbarbero** [comment]
So first thing I would recommend: write a test reproducing current issue that fails with current code. Then modify the code (probably the fix you did in this PR) until the test passes.

**Comment by chrisguindon** [comment]
@mbarbero +1 I already spoke to Martin this morning about writing tests for this.

**Review by mbarbero — APPROVED** [review]

**Pull request merged**
